name: clean_architecture_with_bloc_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Service locator
  get_it: ^2.0.1
  # Bloc for state management
  flutter_bloc: ^7.0.1
  # Value equality
  equatable: ^0.4.0
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  connectivity_plus: ^2.1.0

  # Http calls
  http: ^0.13.0
  # Local cache
  shared_preferences: ^0.5.3+4
  # Json annotator
  json_annotation: ^4.0.1
  # API manager
  chopper: ^4.0.1
  #splash screen
  splashscreen: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # For testing.
  mockito: ^5.0.8
  # Code generator
  build_runner: ^2.0.4
  # Code generator from models (to json and from json)
  json_serializable: ^4.1.3
  # API code generator
  chopper_generator: ^4.0.1
  #Integration tests
  flutter_driver:
    sdk: flutter
  test: any
  #bloc testing
  bloc_test: ^8.0.2



flutter:

  uses-material-design: true

  assets:
    - images/logo.png

  fonts:
   - family: Roboto
     fonts:
       - asset: fonts/Roboto-Regular.ttf
       - asset: fonts/Roboto-Bold.ttf
